# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provision 'shell', path: 'install-python'
  config.vm.provision :file, source: '../../client-server-app/', destination: '/tmp/crossover/'
end
